source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ApiService_Example', :exclusive => true do
  pod "ApiService", :path => "../"
end

target 'ApiService_Tests', :exclusive => true do
  pod "ApiService", :path => "../"

  
end
